/** Các cột profiles trả về client/API — không gồm password_hash */
export const PROFILE_SELECT_PUBLIC = [
  'id',
  'full_name',
  'phone',
  'date_of_birth',
  'gender',
  'citizen_id',
  'job_title',
  'department',
  'personal_email',
  'emergency_contact_name',
  'emergency_contact_phone',
  'emergency_contact_relationship',
  'city',
  'district',
  'ward',
  'address_line',
  'temporary_address',
  'role',
  'is_active',
  'avatar_url',
  'email',
  'created_at',
  'updated_at',
].join(', ');
